### ISSUE TITLE
Koodikatselmointi 

### ISSUE THREAD

**Issue by ruusukivi** [JVS23/Algorithm-comparision-TiRa#1]
**Palaute tehty 15.8. klo 20 kloonatusta versiosta**

Koodia oli helppo lukea ja projekti käynnistyi ongelmitta annetuilla asennusohjeilla. :thumbsup:

Oli hauska huomata, miten eri tavoilla ohjelmaa voi lähteä kokoamaan, toki tässä on varmaan eroja senkin vuoksi, että python on kielenä suoraviivaisempi ja nopeampi kuin java, jolla itse olen vääntänyt :smiley: , vrt. [https://www.youtube.com/watch?v=HMsAfaKGaB8](https://www.youtube.com/watch?v=HMsAfaKGaB8) 

### Huomioita koodista

-  Algoritmeja oli testattu vasta muutamalla verkolla eikä koodissa ei ollut juurikaan virheiden käsittelyä yms. mukana. Isoimmilla verkoilla mahdollisia virheitä voi olla ilman näitä työlästä löytää. 
-  Vaikka ohjelma on vielä pieni, niin erottaisin ainakin testit omaan hakemistoonsa vaikka muuten hierarkisuutta ei haluaisi lisätä.

- [Main.py](https://github.com/JVS23/Algorithm-comparision-TiRa/blob/master/src/main.py): UI-osuuden voisi irroittaa omaksi metodikseen tai tiedostokseen.

- [Algorithms.py](https://github.com/JVS23/Algorithm-comparision-TiRa/blob/master/src/algorithms.py):
Voi olla että python-lukutaitoni on ruosteessa, mutta jäin ihmettelemään, miksi rivillä 24  prioriteettijonoon lisätään tutkittava näin _pq.put((start, 0))_  ja rivillä 41 näin _pq.put((new_cost, neighbor))_ - eikö tuossa ole arvot väärinpäin? Jos on ok, niin ehkä voisi  miettiä muuttujien nimiä havainnollisemmiksi tai vähän selittää enemmän auki.

Networkx vaikutti fiksulta valinnalta, hyvännäköisiä graafeja suoraviivaisesti!

Hyvää duunia ja tsemppiä loppurutistukseen!

**Comment by JVS23** [comment]
Kiitos palautteesta!
