### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by rheikkinen** [JVS23/Algorithm-comparision-TiRa#2]
# Vertaisarvionti, viikko 6
Projekti kloonattu ke 24.8. noin klo 14

### Ohjelman toiminta
Ohjelman suorittaminen onnistui komentoriviltä ja suoraan vscodessa täysin ongelmitta, hyvä! Verkon visualisointiin on myös löydetty varsin selkeä työkalu. 

Kokeilin useammilla verkoilla ja dijkstra näytti toimivan odotetusti. Tosin kokeiltuani eri lähtö- ja maalisolmuja huomasin, että algoritmi toimi kunnolla ainoastaan, kun lähtösolmuna oli 0. Tämä korjaantui hyvinkin pienellä muutoksella `algorithms.py`:ssä: 
- Vaihdoin [**rivillä 24**](https://github.com/JVS23/Algorithm-comparision-TiRa/blob/4d646a92abd4b251963575041cd4ce219bfe232b/src/algorithms.py#L24) `pq.put((start, 0))` parametrit toisinpäin, eli --> `pq.put((0, start))`, minkä jälkeen dijkstra antoi oikeita tuloksia myös muilla aloitussolmuilla.

### Huomio dijkstran lyhimmästä polusta
Algoritmin toteutus on hyvällä mallilla, ja lyhimpien polkujenkin määrittäminen pitäisi olla melko suoraviivaista toteuttaa, joten tässä siihen joitain ideoita:
- Voisi lisätä sopivan tietorakenteen, joka pitää kirjaa solmujen edellisistä naapureista lyhimmällä polulla 
    - Kuvaava nimi voisi tässä tapauksessa olla `previous`, jolloin esim. `previous[2]` olisi solmua 2 edeltävä solmu lyhimmällä polulla 
- Kun parempi etäisyys löytyy (`new_cost < old_cost`), lisättäisiin solmu `current` uudeksi edeltäjäksi solmulle `neighbor`.
- Lopuksi lyhimmän polun saa kasaan hakemalla maalisolmusta lähtösolmuun saakka jokaisen solmun edeltäjän.
    - Tämän voi tietenkin tehdä kaikille solmuille vaihtamalla maalisolmua.
    -  Lyhimmät polut voi tällöin tallettaa avain-arvo-pareina `paths`:iin, mikä ilmeisesti ollut ajatuksena.
    - Avaimena voisi siis olla maalisolmu ja arvona lyhin polku listana tai muuna tietorakenteena.

### Muita huomiota
- Koodin dokumentaatio on kattavasti kirjoitettu, ja koodia oli pääosin oikein sujuva lukea.
- Graph-luokan satunnaisen verkon luova metodi `gen` on oiva lisäys, se helpottaa kokeilua.
    -  Hieman toissijaisena huomiona, metodin voisi kenties nimetä kuvaavammin/pidemmin, mikä parantaisi koodin luettavuutta. 
    - Toisena esimerkkinä metodi `add` voisi olla kuvaavammin `add_edge`
    - Muutenkin metodien ja muuttujien lyhentämistä on hyvä välttää, jos mahdollista.
- Testien ajaminen onnistuu, hyvä! 
    - Testauksessa voisi erilaisten verkkojen lisäksi testata myös samaa verkkoa juurikin eri lähtö- ja maalisolmuilla.
    - Testit voisi myös erotella omaan hakemistoon rakenteen selkeyttämiseksi.
- Muuten rakenne on selkeä, ja koska ohjelma ei ole järin suuri, niin eri osien tarkoitus on helposti ymmärrettävissä.

### Yhteenveto
Ohjelma on vielä hieman keskeneräinen aihemäärittelyyn nähden, mutta hyviä toteutuksia on saatu jo paljon aikaiseksi, ja pohja on hyvällä mallilla projektin viemiseksi eteenpäin. En valitettavasti osannut IDA*:in toteutukseen ottaa kantaa, mutta vielä on aikaa sekin ratkaista ennen loppupalautusta. Aihe on mielenkiintoinen, tsemppiä viimeisiin palautuksiin! :)

**Comment by JVS23** [comment]
Kiitoksia erittäin ammattimaisesta vertaisarvioinnista! Erinomaisia huomioita ja vinkkejä, annoit hyvää uutta näkökulmaa minkä kannalta pohtia omaa koodiani, joten tämän avulla on huomattavasti helpompi lähteä hoitamaan hommaa loppuun.
